name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # 这个值是保留给系统的空间大小，之前设置太小，总会在安装依赖或者编译过程中报设备空间不足的错误而导致编译失败
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dep
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq gpg python3-pyquery wget xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev git lsb vim libelf-dev neofetch python3-pip python3-tk debhelper

      - name: Build
        run: bash build_action.sh


      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
          
      - name: Commit and Push Changes
        if: steps.update-kernel.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "XXTXTOP"
          git config user.email "xxtxtop@gmail.com"
          ls -al
          pwd
          cp /tmp/mainline.txt  ${{ github.workspace }}/txt/mainline.txt
          cp /tmp/mainlineurl.txt ${{ github.workspace }}/txt/mainlineurl.txt
          cp /tmp/stable.txt ${{ github.workspace }}/txt/stable.txt 
          cp /tmp/stableurl.txt ${{ github.workspace }}/txt/stableurl.txt
          cp /tmp/longterm.txt ${{ github.workspace }}/txt/longterm.txt
          cp /tmp/longtermurl.txt ${{ github.workspace }}/txt/longtermurl.txt 
          
          git add ${{ github.workspace }}/txt/mainline.txt  ${{ github.workspace }}/txt/mainlineurl.txt ${{ github.workspace }}/txt/stable.txt ${{ github.workspace }}/txt/stableurl.txt ${{ github.workspace }}/txt/longterm.txt ${{ github.workspace }}/txt/longtermurl.txt

          git commit -m "Create file with kernel version"
          git push 

